stages:
  - deploy

pages:
  stage: deploy
  image: python:3.8
  before_script:
    - apk update && apk add make
    - python -m pip install -r requirements.txt
    - python -m pip install sphinx sphinx-rtd-theme
  script:
    - python -c "import nltk; nltk.download('stopwords')"
    - cd docs && make clean html
  after_script:
    - mv docs/build/html/ ./public/
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
